export const ROUTE_NAMES = {
  HOME:                   "index",
  SHOP:                   "(shop)",
  CHECKOUT:               "checkout/[id]",
  COVERAGE:               "coverage",
  COVERAGE_MODAL:         "coverage-modal",
  WALLET:                 "(wallet)",
  PHONE:                  "phone",
  ORDERS:                 "orders",
  SETTINGS:               "settings",
  BY_COUNTRY:             "country/[id]",
  BY_REGION:              "region/[id]",
  TOKENS:                 "tokens",
  TRANSACTIONS:           "transactions",
  TRANSACTIONDETAILS:     "transactionDetails",
  INSTALLATION:           "installation",
  OFFLINE:                "Offline",
  CONTACTS:               "(contacts)",
  CONTACTS_SCREEN:        "contactsScreen",
  ADD_CONTACTS_SCREEN:    "addContactScreen",
  QR_CODE_SCREEN:         "qrCodeScreen",
  CONTACT_DETAILS:        "contactDetails",
  EDIT_CONTACT:           "editContact",
  SEND_TO_CONTACT:        "sendToContact",
  CONTACT_TRANSACTIONS:   "contactTransactions",
} as const;

export type RouteName = (typeof ROUTE_NAMES)[keyof typeof ROUTE_NAMES];

export const TAB_BAR_ENABLED_ROUTES: string[] = [
  ROUTE_NAMES.HOME,
  ROUTE_NAMES.SHOP,
  `${ROUTE_NAMES.SHOP}/${ROUTE_NAMES.HOME}`,
  `${ROUTE_NAMES.SHOP}/${ROUTE_NAMES.HOME}/Countries`,
  `${ROUTE_NAMES.SHOP}/${ROUTE_NAMES.HOME}/Regions`,
  `${ROUTE_NAMES.SHOP}/${ROUTE_NAMES.HOME}/Global`,
  ROUTE_NAMES.WALLET,
  ROUTE_NAMES.ORDERS,
  ROUTE_NAMES.SETTINGS,
  `${ROUTE_NAMES.WALLET}/${ROUTE_NAMES.TOKENS}`,
  `${ROUTE_NAMES.WALLET}/${ROUTE_NAMES.TRANSACTIONS}`,
  `${ROUTE_NAMES.WALLET}/${ROUTE_NAMES.HOME}`,
];
