name: Create dev builds

defaults:
  tools:
    node: "24.18.0"
    corepack: true

on:
  push:
    branches: ['dev']

jobs:
  android_development_build:
    name: Build Android dev
    type: build
    params:
      platform: android
      profile: development

  ios_device_development_build:
    name: Build iOS dev device
    type: build
    params:
      platform: ios
      profile: development
