name: Deploy production (Android)

jobs:
  build_android:
    name: Build Android
    type: build
    params:
      platform: android
      profile: production

  submit_android:
    name: Submit Android to Play production
    needs: [build_android]
    type: submit
    environment: production
    params:
      build_id: ${{ needs.build_android.outputs.build_id }}
      profile: production
