name: Deploy staging (iOS)

jobs:
  build_ios:
    name: Build iOS
    type: build
    params:
      platform: ios
      profile: staging

  distribute_ios_testflight:
    name: Distribute iOS to TestFlight
    needs: [build_ios]
    type: testflight
    environment: preview
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
      profile: staging
      external_groups: ["Public"]
      submit_beta_review: true
