name: Publish staging OTA (Android)

defaults:
  tools:
    node: "24.18.0"
    corepack: true

jobs:
  publish_android_update:
    name: Publish Android staging OTA update
    type: update
    environment: preview
    params:
      branch: staging
      platform: android
