name: Publish staging OTA

jobs:
  publish_android_update:
    name: Publish Android staging OTA update
    type: update
    environment: preview
    params:
      branch: staging
      platform: android

  publish_ios_update:
    name: Publish iOS staging OTA update
    type: update
    environment: preview
    params:
      branch: staging
      platform: ios
