name: Publish production OTA

jobs:
  publish_android_update:
    name: Publish Android production OTA update
    type: update
    environment: production
    params:
      branch: production
      platform: android

  publish_ios_update:
    name: Publish iOS production OTA update
    type: update
    environment: production
    params:
      branch: production
      platform: ios
