name: Publish production OTA (iOS)

defaults:
  tools:
    node: "24.18.0"
    corepack: true

jobs:
  publish_ios_update:
    name: Publish iOS production OTA update
    type: update
    environment: production
    params:
      branch: production
      platform: ios
